name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        DB_BALAM_TEST_ENGINE: ${{ secrets.DB_BALAM_TEST_ENGINE }}
        DB_BALAM_TEST_USER: ${{ secrets.DB_BALAM_TEST_USER }}
        DB_BALAM_TEST_PASSWORD: ${{ secrets.DB_BALAM_TEST_PASSWORD }}
        DB_BALAM_TEST_HOST: ${{ secrets.DB_BALAM_TEST_HOST}}
        DB_BALAM_TEST_PORT: ${{ secrets.DB_BALAM_TEST_PORT}}
        DB_BALAM_TEST_NAME: ${{ secrets.DB_BALAM_TEST_NAME}}
        PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Ejecutar Comandos de Pythcleon
        run: |
          python --version
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=test/balam --cov-report=xml test/balam/test_database_queries.py

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml
          fail_ci_if_error: true 
          verbose: true 

      